import os

SERPAPI_KEY = os.environ.get("SERPAPI_KEY")
SERPAPI_SEARCH_QUERIES = os.environ.get("SERPAPI_SEARCH_QUERIES").split(',')

GOOGLE_GEOTARGET_COUNTRY_CODE = os.environ.get("GOOGLE_GEOTARGET_COUNTRY_CODE")
GOOGLE_GEOTARGET_TARGET_TYPE = os.environ.get("GOOGLE_GEOTARGET_TARGET_TYPE")

FRANCE_UULE_CODE = os.environ.get('FRANCE_UULE_CODE')
FRANCE_CANONICAL_NAME = os.environ.get('FRANCE_CANONICAL_NAME')

DB_PATH = os.environ.get("DB_PATH")

# POSGRES VAR
POSTGRES_USER=os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD=os.environ.get("POSTGRES_PASSWORD")
POSTGRES_LOCALHOST=os.environ.get("POSTGRES_LOCALHOST")
POSTGRES_GCS_HOST=os.environ.get("POSTGRES_GCS_HOST")
POSTGRES_PORT=os.environ.get("POSTGRES_PORT")
POSTGRES_DATABASE=os.environ.get("POSTGRES_DATABASE")


# OPENAI VAR
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

LANG_CLASSIF_MODEL = os.environ.get('LANG_CLASSIF_MODEL')
ARIA_70B_QUANTIZED = os.environ.get('ARIA_70B_QUANTIZED')
FT_DATASET_HF= os.environ.get('FT_DATASET_HF')

# HUGGIGNFACE
HF_TOKEN = os.environ.get('HF_TOKEN')